<?php
/**
 * @author Jhonathan da silva
 * @link https://github.com/jhonathan93
 * @link https://www.linkedin.com/in/jhonathan-silva-367541171/
 * @package Jhonathan_Core
 */

use Magento\Customer\Block\Widget\Telephone;
use Magento\Customer\Helper\Address;

/**
 * @var Telephone $block
 */

?>

<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?> Jhonathan">
    <label for="telephone" class="label">
        <span>
            <?= $block->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <div class="control">
        <?php
            $_validationClass = $block->escapeHtmlAttr($this->helper(Address::class)->getAttributeValidationClass('telephone'));
        ?>
        <input type="text"
               name="telephone"
               id="telephone"
               value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text <?= $_validationClass ?: '' ?>"
        >
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "init": {
                "elements" : {
                    "0": "input#telephone"
                },

                "mask" : {
                    "0": "(00) 00000-0000"
                },

                "validate": {
                    "0": "false"
                }
            }
        }
    }
</script>
