<?php
/**
 * @author Jhonathan da silva
 * @link https://github.com/jhonathan93
 * @link https://www.linkedin.com/in/jhonathan-silva-367541171/
 * @package Jhonathan_RibbonMarketing
 *
 * @var $block Jhonathan\RibbonMarketing\Block\Ribbon;
 */
?>

<?php if ($block->isEnable()): ?>
    <div class="rm-content-main">
        <h1 class="rm-title">
            <span><?= $block->getTitle(); ?></span>
        </h1>
    </div>
<?php endif; ?>
